import { Message } from "@/types";

export const messages: Message[] = [
  {
    id: "global_message_1",
    name: "Member 1, Member 2, Member 3",
    lastMessage: "Group 2 Message",
    isGroup: true,
    unreadCount: 0,
    muted: false,
    online: false,
    time: "Yesterday",
  },
  {
    id: "global_message_2",
    name: "Group 2",
    lastMessage: "contact@apple.com",
    isGroup: true,
    unreadCount: 4,
    muted: true,
    online: false,
    time: "07:52 AM",
  },
  {
    id: "global_message_3",
    name: "DM User 1",
    lastMessage: "DM Last Message",
    isGroup: false,
    unreadCount: 0,
    muted: false,
    online: true,
    time: "Yesterday",
  },
  {
    id: "global_message_4",
    name: "Muted User 1",
    lastMessage: "Test mute?",
    isGroup: false,
    unreadCount: 1,
    muted: true,
    online: true,
    time: "Yesterday",
  },
  {
    id: "global_message_5",
    name: "Uat User 1",
    lastMessage: "hi hi @ua",
    isGroup: false,
    unreadCount: 0,
    muted: false,
    online: true,
    time: "Yesterday",
  },
  {
    id: "global_message_6",
    name: "Akira, Ramdas, Kumar, Kamlesh",
    lastMessage: "Hello",
    isGroup: true,
    unreadCount: 0,
    muted: false,
    online: false,
    time: "14/07/2026",
  },
  {
    id: "global_message_7",
    name: "Alex, Amogh, Devin, Devine, Sohpie",
    lastMessage:
      "New Group Parent Edited Again Without Changing Its position and Preserving Visual Cues",
    isGroup: true,
    unreadCount: 10,
    muted: false,
    online: false,
    time: "13/07/2026",
  },
];

export const sectionTypes = [
  { type: "All", header: "Messages" },
  { type: "Draft", header: "Drafts" },
  { type: "Sent", header: "Sent" },
  { type: "Unread", header: "Unread" },
  { type: "Saved", header: "Saved" },
  { type: "Mentions", header: "Mentions" },
  { type: "Blocked", header: "Blocked" },
  { type: "Archived", header: "Archived" },
];
